// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Hackaton.API.Data;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Hackaton.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241006221945_New")]
    partial class New
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);
            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hackaton.shared.Entities.HackatonTable", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("FinishDate")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("InitDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Organizer")
                    .IsRequired()
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Topic")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.HasKey("Id");

                b.ToTable("HackatonTables");
            });

            modelBuilder.Entity("Hackaton.shared.Entities.Participant", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Experience")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<int>("RolId")
                    .HasColumnType("int");

                b.Property<int>("TeamId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("RolId");

                b.HasIndex("TeamId");

                b.ToTable("Participants");
            });

            modelBuilder.Entity("Hackaton.shared.Entities.Project", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Description")
                    .HasMaxLength(250)
                    .HasColumnType("nvarchar(250)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<DateTime>("DeliveryDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Score")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("TeamId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("Status");

                b.HasIndex("TeamId");

                b.ToTable("Projects");
            });

            modelBuilder.Entity("Hackaton.shared.Entities.Team", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(100)");

                b.Property<int>("MentorId")
                    .HasColumnType("int");

                b.Property<int>("HackatonId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("MentorId");

                b.HasIndex("HackatonId");

                b.ToTable("Teams");
            });

            modelBuilder.Entity("Hackaton.shared.Entities.Mentor", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Expertise")
                    .IsRequired()
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("IdentificationNumber")
                    .IsRequired()
                    .HasColumnType("nvarchar(50)");

                b.HasKey("Id");

                b.ToTable("Mentors");
            });

            modelBuilder.Entity("Hackaton.shared.Entities.Evaluation", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("MentorId")
                    .HasColumnType("int");

                b.Property<int>("ProjectId")
                    .HasColumnType("int");

                b.Property<string>("Score")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Comments")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("MentorId");

                b.HasIndex("ProjectId");

                b.ToTable("Evaluations");
            });

            modelBuilder.Entity("Hackaton.shared.Entities.Award", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Awards")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<int>("HackatonId")
                    .HasColumnType("int");

                b.Property<string>("Position")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("HackatonId");

                b.ToTable("Awards");
            });

            modelBuilder.Entity("Hackaton.shared.Entities.HackatonTable", b =>
            {
                b.Navigation("Awards");
            });
#pragma warning restore 612, 618
        }
    }
}